name: Supa-backup

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run_db_backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      supabase_db_url_base64: ${{ secrets.SUPABASE_DB_URL_BASE64 }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Decode connection string
        run: |
          echo "$supabase_db_url_base64" | base64 -d > /tmp/db_url
          echo "supabase_db_url=$(cat /tmp/db_url)" >> $GITHUB_ENV
      - name: Backup roles
        run: supabase db dump --db-url "$supabase_db_url" -f roles.sql --role-only
      - name: Backup schema
        run: supabase db dump --db-url "$supabase_db_url" -f schema.sql
      - name: Backup data
        run: supabase db dump --db-url "$supabase_db_url" -f data.sql --data-only --use-copy
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Supabase backup
